def bind_russian(config):
#top row
    config.bind('<Ctrl-К>', 'command-history-prev')
    config.bind('е', 'prompt-accept yes')
    config.bind('ее', 'yank')
    config.bind('еЕ', 'yank -s')
    config.bind('Г', 'move-to-end-of-document')
    config.bind('ГГ', 'move-to-start-of-document')
    config.bind('гы', 'set-cmd-text -s :open {url:pretty}')
    config.bind('гЫ', 'set-cmd-text -s :open -t {url:pretty}')
    config.bind('щ', 'reload')
    config.bind('Щ', 'reload -f')
    config.bind('з', 'scroll right')
    config.bind('З', 'forward')

#middle row
    config.bind('ы', 'set-cmd-text -s :open')
    config.bind('Ы', 'set-cmd-text -s :open -t')
    config.bind('в', 'hint')
    config.bind('В', 'hint all tab')
    config.bind('а', 'undo');
    config.bind('р', 'tab-close')
    config.bind('Р', 'tab-close -o')
    config.bind('о', 'scroll left')
    config.bind('О', 'back')
    config.bind('д', 'search-next')
    config.bind('д', 'prompt-accept no')
    config.bind('Д', 'search-prev')
    config.bind('<Ctrl-Д>', 'command-history-next')

#bottom row
    config.bind('ч', 'spawn ~/scripts/stream.sh {url}')
    config.bind('Ч', 'hint links spawn ~/scripts/stream.sh {hint-url}')
    config.bind('с', 'scroll down')
    config.bind('С', 'tab-next')
    config.bind('<Ctrl-и>', 'prompt-open-download')
    config.bind('м', 'scroll up')
    config.bind('М', 'tab-prev')
    config.bind('т', 'set-cmd-text -s :quickmark-load')
    config.bind('Т', 'set-cmd-text -s :quickmark-load -t')
    config.bind('ь', 'quickmark-save')
