#!/bin/sh

ibase=$1; shift 1
obase=$1; shift 1

if [ -n "$*" ]; then
    cmd=$(echo "$*" | tr '[:lower:]' '[:upper:]')
    echo "obase=$obase; ibase=$ibase; $cmd" | bc
else
    while read -r cmd; do
        cmd=$(echo "$cmd" | tr '[:lower:]' '[:upper:]')
        echo "obase=$obase; ibase=$ibase; $cmd" | bc
    done
fi
