import = ["~/.config/alacritty/gruvbox.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
blink_interval = 1000
style = { blinking ="On" }
thickness = 0.1

[env]
TERM = "xterm-256color"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"
